use std::{collections::{BTreeMap,BTreeSet},env,fs,path::Path};
#[derive(Clone,Copy,Debug,PartialEq,Eq,PartialOrd,Ord)] enum Status{Fail,Hold,Pass}
impl Status{fn parse(s:&str)->Result<Self,String>{match s.to_uppercase().as_str(){"FAIL"=>Ok(Self::Fail),"HOLD"=>Ok(Self::Hold),"PASS"=>Ok(Self::Pass),_=>Err(format!("invalid status {s}"))}} fn text(self)->&'static str{match self{Self::Fail=>"FAIL",Self::Hold=>"HOLD",Self::Pass=>"PASS"}}}
fn meet(a:Status,b:Status)->Status{if a<b{a}else{b}}
#[derive(Clone)] struct Root{id:String,kind:String,status:Status,fresh:String}
#[derive(Clone)] struct Bridge{id:String,status:Status}
#[derive(Clone)] struct Nat{bridge:String,status:Status,mode:String,root:String}
#[derive(Clone)] struct PathW{id:String,src:String,dst:String,status:Status}
#[derive(Clone)] struct Assumption{key:String,value:String,status:Status}
#[derive(Default)] struct Packet{id:String,claim:String,source:Option<Status>,final_:Option<Status>,roots:Vec<Root>,degrees:BTreeSet<String>,covers:Vec<(String,String)>,qroots:Vec<(String,String)>,gens:Vec<(String,String,String)>,endpoint:String,bridges:Vec<Bridge>,nats:Vec<Nat>,paths:Vec<PathW>,peq:BTreeMap<(String,String),Status>,ext:BTreeMap<String,Status>,coh:Option<(Status,String)>,anc:Vec<(String,Status)>,pres:BTreeSet<(String,String)>,ass:Vec<Assumption>,defeats:Vec<String>,target:String,just:Vec<(String,String)>,direct:String,requested:Option<Status>}
fn toks(s:&str)->Vec<String>{s.split_whitespace().map(|x|x.trim_matches('"').to_string()).collect()}
fn rstate(r:&Root)->Status{meet(r.status,match r.fresh.as_str(){"LIVE"=>Status::Pass,"STALE"=>Status::Hold,"EXPIRED"=>Status::Fail,_=>Status::Fail})}
fn parse(path:&Path)->Result<Packet,String>{let txt=fs::read_to_string(path).map_err(|e|e.to_string())?;let mut p=Packet::default();let mut st=false;let mut en=false;for (i,raw) in txt.lines().enumerate(){let line=raw.trim();if line.is_empty()||line.starts_with('#'){continue}let t=toks(line);if t.is_empty(){continue}if t[0]=="REALSUBSTITUTE"{if t.len()!=2||t[1]!="0.7"{return Err("expected REALSUBSTITUTE 0.7".into())}st=true;continue}if !st{return Err("packet must begin REALSUBSTITUTE 0.7".into())}if t[0]=="END"{en=true;break}match t[0].as_str(){
"id" if t.len()==2=>p.id=t[1].clone(),
"claim_kind" if t.len()==2=>{let x=t[1].to_uppercase();if !["TRANSPORT_ONLY","BASIS_GENERATED","NEW_EMPIRICAL"].contains(&x.as_str()){return Err("invalid claim_kind".into())}p.claim=x},
"source_authority" if t.len()==2=>p.source=Some(Status::parse(&t[1])?),
"final_authority" if t.len()==2=>p.final_=Some(Status::parse(&t[1])?),
"root" if t.len()==5=>{let k=t[2].to_uppercase();let f=t[4].to_uppercase();if !["EXTERNAL","INTERNAL"].contains(&k.as_str())||!["LIVE","STALE","EXPIRED"].contains(&f.as_str()){return Err("invalid root".into())}p.roots.push(Root{id:t[1].clone(),kind:k,status:Status::parse(&t[3])?,fresh:f})},
"degree" if t.len()==2=>{p.degrees.insert(t[1].clone());},
"cover" if t.len()==3=>p.covers.push((t[1].clone(),t[2].clone())),
"query_root" if t.len()==3=>p.qroots.push((t[1].clone(),t[2].clone())),
"generate" if t.len()==4=>p.gens.push((t[1].clone(),t[2].clone(),t[3].clone())),
"endpoint_query" if t.len()==2=>p.endpoint=t[1].clone(),
"bridge" if t.len()==5=>p.bridges.push(Bridge{id:t[1].clone(),status:Status::parse(&t[4])?}),
"naturality" if t.len()==5=>{let m=t[3].to_uppercase();if !["DEFINITIONAL","FORMAL_EXACT","EMPIRICAL","SELF","UNTESTED"].contains(&m.as_str()){return Err("invalid naturality".into())}p.nats.push(Nat{bridge:t[1].clone(),status:Status::parse(&t[2])?,mode:m,root:t[4].clone()})},
"path" if t.len()==5=>p.paths.push(PathW{id:t[1].clone(),src:t[2].clone(),dst:t[3].clone(),status:Status::parse(&t[4])?}),
"path_equal" if t.len()==4=>{let(mut a,mut b)=(t[1].clone(),t[2].clone());if b<a{std::mem::swap(&mut a,&mut b)}p.peq.insert((a,b),Status::parse(&t[3])?);},
"extension" if t.len()==3=>{let q=t[1].to_uppercase();if !["PRE","POST"].contains(&q.as_str()){return Err("invalid extension".into())}p.ext.insert(q,Status::parse(&t[2])?);},
"coherence" if t.len()==3=>{let q=t[2].to_uppercase();if !["CLOSED","FINITE_ONLY","OPEN"].contains(&q.as_str()){return Err("invalid coherence".into())}p.coh=Some((Status::parse(&t[1])?,q));},
"ancestor" if t.len()==3=>p.anc.push((t[1].clone(),Status::parse(&t[2])?)),
"preserve" if t.len()==3=>{p.pres.insert((t[1].clone(),t[2].clone()));},
"assumption" if t.len()==4=>p.ass.push(Assumption{key:t[1].clone(),value:t[2].to_uppercase(),status:Status::parse(&t[3])?}),
"defeat" if t.len()==2=>{let q=t[1].to_uppercase();if !["REACHABLE","DEAD","FORBIDDEN"].contains(&q.as_str()){return Err("invalid defeat".into())}p.defeats.push(q)},
"justification_target" if t.len()==2=>p.target=t[1].clone(),
"justify" if t.len()==3=>p.just.push((t[1].clone(),t[2].clone())),
"direct_receipt" if t.len()==2=>{let q=t[1].to_uppercase();if !["ABSENT","PASS","HOLD","FAIL"].contains(&q.as_str()){return Err("invalid direct".into())}p.direct=q},
"authorize" if t.len()==2=>p.requested=Some(Status::parse(&t[1])?),
_=>return Err(format!("{}:{} malformed {line}",path.display(),i+1))}}if !en{return Err("missing END".into())}if p.id.is_empty()||p.claim.is_empty()||p.source.is_none()||p.final_.is_none()||p.roots.is_empty()||p.bridges.is_empty()||p.endpoint.is_empty()||p.target.is_empty()||p.direct.is_empty()||p.requested.is_none(){return Err("missing required v0.7 field".into())}Ok(p)}
fn rmap<'a>(p:&'a Packet)->BTreeMap<&'a str,&'a Root>{p.roots.iter().map(|r|(r.id.as_str(),r)).collect()}
fn used(p:&Packet)->BTreeSet<String>{let mut s=BTreeSet::new();for(_,r)in&p.covers{s.insert(r.clone());}for(_,r)in&p.qroots{s.insert(r.clone());}for n in&p.nats{if n.mode=="EMPIRICAL"&&n.root!="NONE"{s.insert(n.root.clone());}}s}
fn c_external(p:&Packet)->Status{let m=rmap(p);let u=used(p);if u.is_empty(){return Status::Fail}u.into_iter().fold(Status::Pass,|s,id|match m.get(id.as_str()){Some(r)if r.kind=="EXTERNAL"=>meet(s,rstate(r)),_=>Status::Fail})}
fn c_basis(p:&Packet)->Status{if p.degrees.is_empty(){return Status::Hold}let m=rmap(p);let mut out=Status::Pass;for d in&p.degrees{let mut best=Status::Fail;for(dd,x)in&p.covers{if dd==d{if let Some(r)=m.get(x.as_str()){if r.kind=="EXTERNAL"{let q=rstate(r);if q>best{best=q}}}}}if best==Status::Fail{return Status::Fail}out=meet(out,best)}out}
fn c_query(p:&Packet)->Status{let m=rmap(p);let mut f=BTreeSet::new();for(q,x)in&p.qroots{if let Some(r)=m.get(x.as_str()){if r.kind=="EXTERNAL"&&rstate(r)!=Status::Fail{f.insert(q.clone());}}}if f.is_empty(){return Status::Fail}for b in&p.bridges{let ms:Vec<_>=p.gens.iter().filter(|(bb,_,_)|bb==&b.id).collect();if ms.is_empty(){return Status::Hold}let mut n=BTreeSet::new();for(_,a,z)in ms{if f.contains(a){n.insert(z.clone());}}f=n;if f.is_empty(){return Status::Fail}}if f.contains(&p.endpoint){Status::Pass}else{Status::Fail}}
fn c_nat(p:&Packet)->Status{let m=rmap(p);let mut s=Status::Pass;for b in&p.bridges{let Some(n)=p.nats.iter().find(|n|n.bridge==b.id)else{return Status::Hold};if n.mode=="SELF"{return Status::Fail}if n.mode=="UNTESTED"{s=meet(s,Status::Hold);continue}s=meet(s,n.status);if n.mode=="EMPIRICAL"{let Some(r)=m.get(n.root.as_str())else{return Status::Fail};if r.kind!="EXTERNAL"{return Status::Fail}s=meet(s,rstate(r));}}s}
fn c_paths(p:&Packet)->Status{if p.paths.is_empty(){return Status::Hold}let mut s=p.paths.iter().fold(Status::Pass,|a,x|meet(a,x.status));if p.paths.len()==1{return s}let src=&p.paths[0].src;let dst=&p.paths[0].dst;if p.paths.iter().any(|x|&x.src!=src||&x.dst!=dst){return Status::Fail}for i in 0..p.paths.len(){for j in i+1..p.paths.len(){let(mut a,mut b)=(p.paths[i].id.clone(),p.paths[j].id.clone());if b<a{std::mem::swap(&mut a,&mut b)}let Some(q)=p.peq.get(&(a,b))else{return Status::Hold};s=meet(s,*q)}}s}
fn c_cong(p:&Packet)->Status{if p.paths.len()<=1{return Status::Pass}meet(p.ext.get("PRE").copied().unwrap_or(Status::Hold),p.ext.get("POST").copied().unwrap_or(Status::Hold))}
fn c_coh(p:&Packet)->Status{match&p.coh{None=>Status::Hold,Some((Status::Fail,_))=>Status::Fail,Some((s,m))if m=="CLOSED"=>*s,_=>Status::Hold}}
fn c_anc(p:&Packet)->Status{if p.anc.is_empty(){return Status::Hold}let mut s=Status::Pass;for(a,st)in&p.anc{s=meet(s,*st);for b in&p.bridges{if !p.pres.contains(&(b.id.clone(),a.clone())){return Status::Fail}}}s}
fn c_ass(p:&Packet)->Status{let mut m:BTreeMap<&str,&str>=BTreeMap::new();let mut s=Status::Pass;for a in&p.ass{s=meet(s,a.status);if let Some(v)=m.get(a.key.as_str()){if *v!=a.value.as_str(){return Status::Fail}}else{m.insert(a.key.as_str(),a.value.as_str());}}s}
fn c_new(p:&Packet)->Status{if p.claim=="NEW_EMPIRICAL"{Status::Fail}else{Status::Pass}}
fn c_def(p:&Packet)->Status{if p.defeats.is_empty(){Status::Hold}else if p.defeats.iter().all(|x|x=="REACHABLE"){Status::Pass}else{Status::Fail}}
fn reach(n:&str,e:&[(String,String)],ex:&BTreeSet<String>)->bool{let mut seen=BTreeSet::new();let mut st=vec![n.to_string()];while let Some(x)=st.pop(){if ex.contains(&x){return true}if !seen.insert(x.clone()){continue}for(a,b)in e{if a==&x{st.push(b.clone())}}}false}
fn c_ext(p:&Packet)->Status{let ex:BTreeSet<String>=p.roots.iter().filter(|r|r.kind=="EXTERNAL").map(|r|r.id.clone()).collect();if ex.is_empty(){return Status::Fail}let mut nodes=BTreeSet::new();let mut st=vec![p.target.clone()];while let Some(x)=st.pop(){if !nodes.insert(x.clone()){continue}for(a,b)in&p.just{if a==&x{st.push(b.clone())}}}if nodes.into_iter().all(|n|reach(&n,&p.just,&ex)){Status::Pass}else{Status::Fail}}
fn c_bridge(p:&Packet)->Status{p.bridges.iter().fold(Status::Pass,|a,b|meet(a,b.status))}
fn c_global(p:&Packet)->Status{let mut c=p.source.unwrap();for(_,s)in&p.anc{c=meet(c,*s)}for a in&p.ass{c=meet(c,a.status)}let m=rmap(p);for x in used(p){if let Some(r)=m.get(x.as_str()){c=meet(c,rstate(r));}}if p.final_.unwrap()>c{Status::Fail}else{Status::Pass}}
fn c_direct(p:&Packet)->Status{match p.direct.as_str(){"ABSENT"|"PASS"=>Status::Pass,"HOLD"|"FAIL"=>Status::Hold,_=>Status::Fail}}
fn derive(p:&Packet)->BTreeMap<&'static str,Status>{let base=[("external_root",c_external(p)),("world_contact_basis",c_basis(p)),("query_basis",c_query(p)),("naturality",c_nat(p)),("path_independence",c_paths(p)),("congruence",c_cong(p)),("higher_coherence",c_coh(p)),("ancestry",c_anc(p)),("assumption",c_ass(p)),("no_new_empirical_degree",c_new(p)),("defeat_to_world",c_def(p)),("exteriority",c_ext(p)),("bridge_state",c_bridge(p)),("global_nonamplification",c_global(p)),("direct_conflict",c_direct(p))];let mut d:BTreeMap<&'static str,Status>=base.into_iter().collect();let s=d.values().copied().fold(Status::Pass,meet);d.insert("substitution",s);d}
fn mincover(p:&Packet)->Option<usize>{let rs:Vec<_>=p.roots.iter().filter(|r|r.kind=="EXTERNAL"&&rstate(r)==Status::Pass).map(|r|r.id.clone()).collect();if p.degrees.is_empty()||rs.len()>20{return None}for k in 0..=rs.len(){for mask in 0usize..(1usize<<rs.len()){if mask.count_ones()as usize!=k{continue}let chosen:BTreeSet<&str>=rs.iter().enumerate().filter(|(i,_)|mask&(1usize<<i)!=0).map(|(_,x)|x.as_str()).collect();if p.degrees.iter().all(|d|p.covers.iter().any(|(dd,r)|dd==d&&chosen.contains(r.as_str()))){return Some(k)}}}None}
fn emit(p:&Packet,d:&BTreeMap<&'static str,Status>)->String{let mut o=vec!["REAL-SUBSTITUTION=0.7".into(),format!("id={}",p.id),format!("claim_kind={}",p.claim),format!("source_authority={}",p.source.unwrap().text()),format!("final_authority={}",p.final_.unwrap().text()),format!("direct_receipt={}",p.direct)];for k in["external_root","world_contact_basis","query_basis","naturality","path_independence","congruence","higher_coherence","ancestry","assumption","no_new_empirical_degree","defeat_to_world","exteriority","bridge_state","global_nonamplification","direct_conflict","substitution"]{o.push(format!("coordinate.{k}={}",d[k].text()));}o.push(format!("wcb.declared_degree_count={}",p.degrees.len()));o.push(format!("wcb.minimum_declared_roots={}",mincover(p).map(|x|x.to_string()).unwrap_or_else(||"UNAVAILABLE".into())));o.extend(["substitution.meaning=WORLD_CONTACT_BASIS_PRESERVING_NONAMPLIFYING","fresh_direct_endpoint_contact_is_not_universally_required=true","internal_coherence_does_not_create_world_contact=true","path_agreement_is_not_independent_world_contact=true","derived_receipts_do_not_refresh_world_roots=true","later_direct_conflict_reopens_substitution=true","final_truth_distance=UNIDENTIFIED"].iter().map(|x|x.to_string()));o.join("\n")+"\n"}
fn main(){let a:Vec<String>=env::args().skip(1).collect();if a.is_empty(){std::process::exit(2)}for f in a{match parse(Path::new(&f)){Ok(p)=>{let d=derive(&p);let got=d["substitution"];if p.requested.unwrap()>got{eprintln!("SUBSTITUTION_LAUNDERING: requested {} above derived {}",p.requested.unwrap().text(),got.text());std::process::exit(1)}print!("{}",emit(&p,&d));},Err(e)=>{eprintln!("{e}");std::process::exit(1)}}}}
